version: '3'
services:
  db:
    image: mysql:5.7.23
    environment:
      MYSQL_ROOT_PASSWORD: root_on_rails
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  web:
    build: .
    command: >
      bash -c "dockerize -wait tcp://db:3306
      && rake db:create
      && bin/rails db:migrate RAILS_ENV=development
      && bin/webpack
      && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mujin
    ports:
      - "3000:3000"
    depends_on:
      - db
